name: Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        shell: bash
        run: |
          pnpm run test

      - name: Build App
        shell: bash
        run: |
          pnpm run build

      - name: Pack
        uses: a7ul/tar-action@v1.1.2
        with:
          command: c
          cwd: "./"
          files: |
            package.json
            pnpm-lock.yaml
            assets
            backend
            server
            app.vue
            nuxt.config.ts
            tailwind.config.ts
            tsconfig.ts
            assets
            Dockerfile
            captain-definition
          outPath: deploy.tar

      - name: Deploy App
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
